#CI Test - Build the action container
# build test container which has default test files and validate
name: CI
on: [push] 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Merge Sarif Files for github scans
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls 
        run: | 
          ls -al 
          du -a 
      - name: Merge first file into merged.sarif 
        uses: ./   
        with:
          input-file-name: ./test/frontend.sarif
          merged-file-name: ./test/merged.sarif  
      - name:  Merge first file into merged.sarif
        uses: ./   
        with:
          input-file-name: ./test/fib-go.sarif
          merged-file-name: ./test/merged.sarif
      - name: Cat Result
        run: | 
          cat ./test/merged.sarif | jq  