#CI Test - Build the action container
# build test container which has default test files and validate
name: CI
on: [push] 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Merge Sarif Files for github scans
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls
        uses: ubuntu-latest
        run: | 
          ls -al 
          du -a 
      - name: Run local action
        uses: ./   
        with:
          input-file-name: ./test/snyk.sarf
          merged-file-name: ./test/merged.sarf  